config/routes.rb
SupermarketCheckout::Application.routes.draw do

  root :to => 'products#index'

  get "store/checkout"

  resources :basket_items

  resources :products

end

app/models/basket_item.rb
class BasketItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :checkout

  attr_accessible :product, :quantity

  def price
    product.price
  end

end

app/models/checkout.rb
class Checkout < ActiveRecord::Base
  include CheckoutPriceCalculator
  has_many :basket_items, :dependent => :destroy

  def scan (item)
    item_already_in_basket = basket_items.find_by_product_id(item.product.id)

    if item_already_in_basket
      item_already_in_basket.quantity += 1
      item_already_in_basket.save!
    else
      basket_items << item
    end
  end

  def total
    total = 0

    basket_items.each do |item|
      price = checkout_price_for(item)
      total += price
    end

    return total
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :basket_items, :dependent => :restrict

  attr_accessible :name, :price, :product_code
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def current_checkout
    Checkout.find(session[:checkout_id])
  rescue ActiveRecord::RecordNotFound
    checkout = Checkout.create
    session[:checkout_id] = checkout.id
    checkout
  end
end

app/controllers/basket_items_controller.rb
class BasketItemsController < ApplicationController
  # GET /basket_items
  # GET /basket_items.json
  def index
    @basket_items = BasketItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @basket_items }
    end
  end

  # GET /basket_items/1
  # GET /basket_items/1.json
  def show
    @basket_item = BasketItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @basket_item }
    end
  end

  # GET /basket_items/new
  # GET /basket_items/new.json
  def new
    @basket_item = BasketItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @basket_item }
    end
  end

  # GET /basket_items/1/edit
  def edit
    @basket_item = BasketItem.find(params[:id])
  end

  # POST /basket_items
  # POST /basket_items.json
  def create
    checkout = current_checkout

    product = Product.find(params[:product_id])
    @basket_item = BasketItem.new(:product => product)

    scanned_at_checkout = true
    if @basket_item.save
      checkout.scan(@basket_item)
    else
      scanned_at_checkout = false
    end

    respond_to do |format|
      if scanned_at_checkout
        format.html { redirect_to product, notice: 'We successfully added that item to your basket.' }
        format.json { render json: @basket_item, status: :created, location: @basket_item }
      else
        format.html { redirect_to product, notice: 'Oops! We were not able to add this to your basket, contact customer services for assistance.' }
        format.json { render json: @basket_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /basket_items/1
  # PUT /basket_items/1.json
  def update
    @basket_item = BasketItem.find(params[:id])

    respond_to do |format|
      if @basket_item.update_attributes(params[:basket_item])
        format.html { redirect_to @basket_item, notice: 'We successfully updated that item in your basket.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @basket_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /basket_items/1
  # DELETE /basket_items/1.json
  def destroy
    @basket_item = BasketItem.find(params[:id])
    @basket_item.destroy

    respond_to do |format|
      format.html { redirect_to basket_items_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def checkout
    @checkout = current_checkout

    respond_to do |format|
      format.html
      format.json { render json: @checkout }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/basket_items/_form.html.erb
<%= form_for(@basket_item) do |f| %>
  <% if @basket_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@basket_item.errors.count, "error") %> prohibited this basket_item from being saved:</h2>

      <ul>
      <% @basket_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :checkout_id %><br />
    <%= f.number_field :checkout_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/basket_items/edit.html.erb
<h1>Editing basket_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @basket_item %> |
<%= link_to 'Back', basket_items_path %>

app/views/basket_items/index.html.erb
<h1>Listing basket_items</h1>

<table>
  <tr>
    <th>Product</th>
    <th>Checkout</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @basket_items.each do |basket_item| %>
  <tr>
    <td><%= basket_item.product_id %></td>
    <td><%= basket_item.checkout_id %></td>
    <td><%= link_to 'Show', basket_item %></td>
    <td><%= link_to 'Edit', edit_basket_item_path(basket_item) %></td>
    <td><%= link_to 'Destroy', basket_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Basket item', new_basket_item_path %>

app/views/basket_items/new.html.erb
<h1>New basket_item</h1>

<%= render 'form' %>

<%= link_to 'Back', basket_items_path %>

app/views/basket_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Product:</b>
  <%= @basket_item.product_id %>
</p>

<p>
  <b>Checkout:</b>
  <%= @basket_item.checkout_id %>
</p>


<%= link_to 'Edit', edit_basket_item_path(@basket_item) %> |
<%= link_to 'Back', basket_items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SupermarketCheckout</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div class="fixed-header"><%= button_to 'Checkout', store_checkout_path, :method => "get" %></div>
<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_code %><br />
    <%= f.text_field :product_code %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
  <tr>
    <th>Product code</th>
    <th>Name</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @products.each do |product| %>
  <tr>
    <td><%= product.product_code %></td>
    <td><%= product.name %></td>
    <td><%= number_to_currency(product.price, :unit => '£') %></td>
    <td><%= link_to 'Show', product %></td>
    <td><%= link_to 'Edit', edit_product_path(product) %></td>
    <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Product code:</b>
  <%= @product.product_code %>
</p>

<p>
  <b>Name:</b>
  <%= @product.name %>
</p>

<p>
  <b>Price:</b>
  <%= number_to_currency(@product.price, :unit => '£') %>
</p>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>
<%= button_to 'Add to Basket', basket_items_path(:product_id => @product) %>

app/views/store/checkout.html.erb
<h1>Items in Your Basket</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Price</th>
    <th>Quantity</th>
  </tr>


  <% my_items = @checkout.basket_items %>
  <% my_items.each do |item| %>
      <tr>
        <td><%= item.product.name %></td>
        <td><%= number_to_currency(item.price, :unit => '£') %></td>
        <td><%= item.quantity.to_s %></td>
      </tr>
  <% end %>

  <tr>
    <td><%='Total: '%></td>
    <td><%= number_to_currency(@checkout.total, :unit => '£') %></td>
  </tr>

</table>

<br />